[tools]
fzf = "latest"
go = "latest"
neovim = "0.11.2"
starship = "latest"
stylua = "latest"
tmux = "latest"
node = "latest"
ripgrep = "latest"
python = "latest"
bat = "latest"
ffmpeg = "latest"
fd = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true
