#!/usr/bin/env bash

candy+=($(find ~ -maxdepth 1 -mindepth 1 -type d))
candy+=($(find ~/projects -maxdepth 1 -mindepth 1 -type d))

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(printf '%s\n' "${candy[@]}" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    if [[ -z $TMUX ]] ; then
        tmux new-session -s $selected_name -c $selected
    else
        tmux new-session -ds $selected_name -c $selected
    fi
fi

if [[ -z $TMUX ]] ; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi
