#!/usr/bin/env bash

candy+=(~/.local/share/nvim)
candy+=($(find ~ -maxdepth 1 -mindepth 1 -type d))
candy+=($(find ~/projects -maxdepth 1 -mindepth 1 -type d))
candy+=($(find ~/tmp -maxdepth 1 -mindepth 1 -type d))
candy+=($(find ~/.local/share/nvim/lazy -maxdepth 1 -mindepth 1 -type d))
candy+=($(find $(cat ~/utils/ts_dirs) -maxdepth 1 -mindepth 1 -type d))

printf '%s\n' "${candy[@]}" | fzf
